
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FamilyNight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FamilyNight
pod 'Firebase/DynamicLinks'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'

end
